# Change these first
owner: VoroninaYanina # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: hub.registry-mirrors.top
    url: https://hub.registry-mirrors.top
  - name: docker.mybacc.com
    url: https://docker.mybacc.com
  - name: docker.zhai.cm
    url: https://docker.zhai.cm
  - name: docker.1ms.run
    url: https://docker.1ms.run
  - name: dytt.online
    url: https://dytt.online
  - name: func.ink
    url: https://func.ink
  - name: lispy.org
    url: https://lispy.org
  - name: xiaogenban1993.com
    url: https://docker.xiaogenban1993.com
  - name: dockerhub.websoft9.com
    url: https://dockerhub.websoft9.com
  - name: docker.m.daocloud.io
    url: https://docker.m.daocloud.io
  - name: hub.xdark.top
    url: https://hub.xdark.top
  - name: dockerhub.timeweb.cloud
    url: https://dockerhub.timeweb.cloud
  - name: dislabaiot.xyz
    url: https://dislabaiot.xyz
  - name: dockerproxy.com
    url: https://dockerproxy.com  
  - name: docker.fxxk.dedyn.io
    url: https://docker.fxxk.dedyn.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: registry-mirrors.top
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: registry-mirrors
  introTitle: "欢迎访问 ***[registry-mirrors.top](https://registry-mirrors.top)***，您的容器镜像加速器状态监控平台。"
  introMessage: "我们致力于为开发者和运维团队提供实时的容器镜像加速器状态监控服务，帮助您快速了解各大镜像镜像加速器的健康状况、响应速度和可用性。通过直观的数据展示和详细的性能分析，registry-mirrors.top 助您优化容器镜像拉取体验，提升开发和部署效率。为您提供精准的监控和告警服务，确保您的容器化应用始终高效运行。"
  navbar:
    - title: Home
      href: https://registry-mirrors.top/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: © 2025 registry-mirrors 容器镜像加速器. All rights reserved.
  activeIncidents: 监控到的故障
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
